### ISSUE TITLE
Salt is not generated properly

### ISSUE THREAD

**Issue by Kshitiz1403** [pspiagicw/placy#26]
![Image](https://user-images.githubusercontent.com/75060259/208882114-743cb886-8a92-4cf9-b816-23e7704bbd3a.png)

Salt should be a very large crypto safe string

**Comment by pspiagicw** [comment]
I know this, still finding a library for hashing in Python. Tried to use `bcrypt`, but it might require C compiler to be installed always. Already tracked in  #20

**Comment by Kshitiz1403** [comment]
Have a look at - https://stackoverflow.com/questions/5293959/creating-a-salt-in-python

**Comment by pspiagicw** [comment]
With the commit e447c00, no salt generation is needed. `passlib` stores the salt along with the password. Thus the `salt` field has been removed from the User ORM model. It makes things a lot easier.1
