### ISSUE TITLE
Potential edge cases when trying to reset the password

### ISSUE THREAD

**Issue by Kshitiz1403** [pspiagicw/placy#27]
![Image](https://user-images.githubusercontent.com/75060259/208882446-d0a17abd-c95d-4aad-986b-a9c6fd46249d.png)

When the user tries to reset the password (OTP has already been generated and recieved), we try to search for a document where the otp hasnt been used and it matches as above in the image.
There might be an edge case where the user has requested for multiple OTPs. Then this would fail.

There are two possible solutions for it - 
1) We maintain only 1 record for earch user's forgot password, i.e. whenever a new request for generating an OTP is generated, we overwrite the previous one.
2) Or while searching for an OTP in our current implementation, we search it in reverse sorted manner sorted to creation time. That way will always be serving the latest OTP request.

**Comment by pspiagicw** [comment]
Okay , I like the 2nd option. I will look into it immediatly.

**Comment by pspiagicw** [comment]
I have implemented the 1st case, the OTP is overriden everytime user requests it. Right now, OTP is stored irrespective of whether user exists or not. Will fix that by next commit.

**Comment by pspiagicw** [comment]
Fixed the entire OTP stuff, in df69b3e

**Comment by Kshitiz1403** [comment]
Great stuff!
