### ISSUE TITLE
Shift to an ORM

### ISSUE THREAD

**Issue by Kshitiz1403** [pspiagicw/placy#28]
Currently any duplicate fields are not handled.
For eg. a user wants to create a new account with a new email but an existing username. S/he will be able to do that which should not be the expected behaviour.
To ensure that, either we make sure to have manual checks at every stage involving mutliple network requests from your server or we use an ORM which handles all of this for us (like creating indexes, etc.)

**Comment by pspiagicw** [comment]
Okay. found MongoEngine, which builds on top of PyMongo.

**Comment by Kshitiz1403** [comment]
@pspiagicw you are my life bro ❤ PS No homo 😂

**Comment by pspiagicw** [comment]
Fixed in 95f43c52
