### ISSUE TITLE
Sort of a mess

### ISSUE THREAD

**Issue by Kshitiz1403** [pspiagicw/placy#29]
Currently we have models on our backend.
Let us have a look at one of the models.
```
class Auth(BaseModel):
    """Model for the user."""

    username: str
    email: EmailStr
    role: RoleEnum
    password: str
    salt: str | None

class User(BaseModel):
    """Model for the user."""

    auth: Auth
    created_at: datetime.datetime
    updated_at: datetime.datetime
    profile_completed: bool

    profile: Profile | None
```
Now this is a User model.
Ofcourse it lacks id (i.e. ObjectID)

But can we add it here? No
Why? Coz we are using this model to create a new record in the database, hence we cannot use the id field.

But id field is required. Right?
Yes. So inorder to fix that, we'll have to use 2 models. 

One would be interfaces - defines the basic fields or the schema.
The second one would be a mongodb model having fields like id, createdAt, updatedAt, etc.

**Comment by pspiagicw** [comment]
Pydantic and MongoEngine work kinda together no problem. I will look into this immediatly.

**Comment by pspiagicw** [comment]
Fixed in 95f43c

**Comment by Kshitiz1403** [comment]
Nice!
